version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: mdd-mongo
    ports:
    - "27017:27017"
    volumes:
    - mongo_data:/data/db

  backend:
    image: mdd-backend
    depends_on:
      - mongo
    environment:
    - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/mdd
    ports:
    - "8080:8080"

  frontend:
    image: mdd-frontend
    container_name: mdd-frontend
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  mongo_data: